-- K-RESET Platform Initial Database Schema
-- Generated by Drizzle ORM
-- This migration creates all the core tables for the platform

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Organizations table - Multi-tenant support
CREATE TABLE "organizations" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "name" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(255) NOT NULL UNIQUE,
  "description" TEXT,
  "logo" TEXT,
  "website" TEXT,
  "settings" JSONB DEFAULT '{}',
  "plan" VARCHAR(50) NOT NULL DEFAULT 'free',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Users table - Core user information and gamification data
CREATE TABLE "users" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "email" VARCHAR(255) NOT NULL UNIQUE,
  "username" VARCHAR(100) UNIQUE,
  "name" VARCHAR(255) NOT NULL,
  "avatar" TEXT,
  "bio" TEXT,
  "role" VARCHAR(50) NOT NULL DEFAULT 'student',
  "permissions" JSONB DEFAULT '[]',
  "level" INTEGER NOT NULL DEFAULT 1,
  "current_xp" INTEGER NOT NULL DEFAULT 0,
  "total_xp" INTEGER NOT NULL DEFAULT 0,
  "current_streak" INTEGER NOT NULL DEFAULT 0,
  "longest_streak" INTEGER NOT NULL DEFAULT 0,
  "last_active_at" TIMESTAMP DEFAULT NOW(),
  "timezone" VARCHAR(50) DEFAULT 'UTC',
  "locale" VARCHAR(10) DEFAULT 'en',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "is_verified" BOOLEAN NOT NULL DEFAULT false,
  "is_banned" BOOLEAN NOT NULL DEFAULT false,
  "preferences" JSONB DEFAULT '{}',
  "notification_settings" JSONB DEFAULT '{}',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "deleted_at" TIMESTAMP
);

-- Curriculum categories
CREATE TABLE "curriculum_categories" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "slug" VARCHAR(255) NOT NULL,
  "color" VARCHAR(7) DEFAULT '#3B82F6',
  "icon" VARCHAR(100),
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "metadata" JSONB DEFAULT '{}',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID REFERENCES "users"("id") NOT NULL
);

-- Curriculum modules
CREATE TABLE "curriculum_modules" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "category_id" UUID NOT NULL REFERENCES "curriculum_categories"("id"),
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "summary" TEXT,
  "difficulty" VARCHAR(50) NOT NULL,
  "estimated_time_minutes" INTEGER NOT NULL,
  "tags" JSONB DEFAULT '[]',
  "prerequisites" JSONB DEFAULT '[]',
  "xp_reward" INTEGER NOT NULL DEFAULT 100,
  "status" VARCHAR(50) NOT NULL DEFAULT 'draft',
  "version" INTEGER NOT NULL DEFAULT 1,
  "published_at" TIMESTAMP,
  "resources" JSONB DEFAULT '[]',
  "attachments" JSON DEFAULT '[]',
  "view_count" INTEGER NOT NULL DEFAULT 0,
  "completion_count" INTEGER NOT NULL DEFAULT 0,
  "average_rating" INTEGER DEFAULT 0,
  "rating_count" INTEGER NOT NULL DEFAULT 0,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "ai_summary" TEXT,
  "ai_tags" JSONB DEFAULT '[]',
  "ai_difficulty" VARCHAR(50),
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id"),
  "updated_by" UUID REFERENCES "users"("id")
);

-- User progress tracking
CREATE TABLE "user_progress" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "module_id" UUID NOT NULL REFERENCES "curriculum_modules"("id"),
  "progress" INTEGER NOT NULL DEFAULT 0,
  "completed_at" TIMESTAMP,
  "time_spent_minutes" INTEGER NOT NULL DEFAULT 0,
  "session_count" INTEGER NOT NULL DEFAULT 0,
  "last_session_at" TIMESTAMP,
  "xp_earned" INTEGER NOT NULL DEFAULT 0,
  "rating" INTEGER,
  "journal_entry" TEXT,
  "notes" TEXT,
  "ai_insights" JSONB DEFAULT '{}',
  "struggling_areas" JSONB DEFAULT '[]',
  "strengths" JSONB DEFAULT '[]',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE("user_id", "module_id")
);

-- Achievements system
CREATE TABLE "achievements" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "category" VARCHAR(50) NOT NULL,
  "icon" VARCHAR(100),
  "color" VARCHAR(7) DEFAULT '#FFD700',
  "rarity" VARCHAR(50) DEFAULT 'common',
  "xp_reward" INTEGER NOT NULL DEFAULT 0,
  "badge_url" TEXT,
  "criteria" JSONB NOT NULL,
  "is_secret" BOOLEAN NOT NULL DEFAULT false,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "unlocked_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID REFERENCES "users"("id")
);

-- User achievements
CREATE TABLE "user_achievements" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "achievement_id" UUID NOT NULL REFERENCES "achievements"("id"),
  "progress" INTEGER NOT NULL DEFAULT 0,
  "unlocked_at" TIMESTAMP,
  "notified_at" TIMESTAMP,
  "metadata" JSONB DEFAULT '{}',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE("user_id", "achievement_id")
);

-- Learning pods (peer groups)
CREATE TABLE "pods" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "avatar" TEXT,
  "invite_code" VARCHAR(50) NOT NULL UNIQUE,
  "is_public" BOOLEAN NOT NULL DEFAULT false,
  "requires_approval" BOOLEAN NOT NULL DEFAULT false,
  "max_members" INTEGER NOT NULL DEFAULT 10,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "settings" JSONB DEFAULT '{}',
  "member_count" INTEGER NOT NULL DEFAULT 0,
  "message_count" INTEGER NOT NULL DEFAULT 0,
  "last_activity_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id")
);

-- Pod membership
CREATE TABLE "pod_members" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pod_id" UUID NOT NULL REFERENCES "pods"("id"),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "role" VARCHAR(50) NOT NULL DEFAULT 'member',
  "status" VARCHAR(50) NOT NULL DEFAULT 'active',
  "permissions" JSONB DEFAULT '[]',
  "message_count" INTEGER NOT NULL DEFAULT 0,
  "last_active_at" TIMESTAMP,
  "joined_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "left_at" TIMESTAMP,
  "invited_by" UUID REFERENCES "users"("id"),
  UNIQUE("pod_id", "user_id")
);

-- Missions system
CREATE TABLE "missions" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "title" VARCHAR(255) NOT NULL,
  "description" TEXT NOT NULL,
  "instructions" TEXT,
  "type" VARCHAR(50) NOT NULL DEFAULT 'challenge',
  "difficulty" VARCHAR(50) NOT NULL,
  "category" VARCHAR(100),
  "xp_reward" INTEGER NOT NULL DEFAULT 200,
  "badge_reward" UUID REFERENCES "achievements"("id"),
  "custom_rewards" JSONB DEFAULT '[]',
  "max_participants" INTEGER NOT NULL DEFAULT 50,
  "min_participants" INTEGER NOT NULL DEFAULT 1,
  "is_team_based" BOOLEAN NOT NULL DEFAULT false,
  "status" VARCHAR(50) NOT NULL DEFAULT 'draft',
  "start_date" TIMESTAMP NOT NULL,
  "end_date" TIMESTAMP NOT NULL,
  "registration_deadline" TIMESTAMP,
  "requirements" JSONB DEFAULT '{}',
  "eligibility_criteria" JSONB DEFAULT '{}',
  "pod_id" UUID REFERENCES "pods"("id"),
  "target_audience" JSONB DEFAULT '{}',
  "is_ai_generated" BOOLEAN NOT NULL DEFAULT false,
  "ai_prompt" TEXT,
  "ai_metadata" JSONB DEFAULT '{}',
  "participant_count" INTEGER NOT NULL DEFAULT 0,
  "completion_count" INTEGER NOT NULL DEFAULT 0,
  "average_completion_time_minutes" INTEGER,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id")
);

-- Mission participation
CREATE TABLE "mission_participation" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "mission_id" UUID NOT NULL REFERENCES "missions"("id"),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "team_id" UUID,
  "status" VARCHAR(50) NOT NULL DEFAULT 'registered',
  "progress" INTEGER NOT NULL DEFAULT 0,
  "score" INTEGER DEFAULT 0,
  "completed_at" TIMESTAMP,
  "xp_earned" INTEGER NOT NULL DEFAULT 0,
  "submission" JSONB DEFAULT '{}',
  "submitted_at" TIMESTAMP,
  "feedback" TEXT,
  "rating" INTEGER,
  "registered_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "started_at" TIMESTAMP,
  UNIQUE("mission_id", "user_id")
);

-- Chat channels
CREATE TABLE "chat_channels" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "pod_id" UUID NOT NULL REFERENCES "pods"("id"),
  "name" VARCHAR(255) NOT NULL,
  "description" TEXT,
  "type" VARCHAR(50) NOT NULL DEFAULT 'general',
  "is_private" BOOLEAN NOT NULL DEFAULT false,
  "settings" JSONB DEFAULT '{}',
  "message_count" INTEGER NOT NULL DEFAULT 0,
  "last_message_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id")
);

-- Chat messages
CREATE TABLE "chat_messages" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "channel_id" UUID NOT NULL REFERENCES "chat_channels"("id"),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "content" TEXT NOT NULL,
  "message_type" VARCHAR(50) NOT NULL DEFAULT 'text',
  "attachments" JSONB DEFAULT '[]',
  "mentions" JSONB DEFAULT '[]',
  "reactions" JSONB DEFAULT '{}',
  "parent_id" UUID REFERENCES "chat_messages"("id"),
  "thread_count" INTEGER NOT NULL DEFAULT 0,
  "is_edited" BOOLEAN NOT NULL DEFAULT false,
  "is_deleted" BOOLEAN NOT NULL DEFAULT false,
  "edited_at" TIMESTAMP,
  "deleted_at" TIMESTAMP,
  "metadata" JSONB DEFAULT '{}',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Notifications
CREATE TABLE "notifications" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "type" VARCHAR(100) NOT NULL,
  "title" VARCHAR(255) NOT NULL,
  "message" TEXT NOT NULL,
  "icon" VARCHAR(100),
  "image" TEXT,
  "action_url" TEXT,
  "action_text" VARCHAR(100),
  "is_read" BOOLEAN NOT NULL DEFAULT false,
  "read_at" TIMESTAMP,
  "channels" JSONB DEFAULT '["in_app"]',
  "delivery_status" JSONB DEFAULT '{}',
  "metadata" JSONB DEFAULT '{}',
  "related_id" UUID,
  "related_type" VARCHAR(100),
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "scheduled_for" TIMESTAMP
);

-- Analytics events
CREATE TABLE "analytics_events" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "user_id" UUID REFERENCES "users"("id"),
  "event" VARCHAR(100) NOT NULL,
  "category" VARCHAR(100),
  "action" VARCHAR(100),
  "label" VARCHAR(255),
  "value" INTEGER,
  "properties" JSONB DEFAULT '{}',
  "user_agent" TEXT,
  "ip_address" VARCHAR(45),
  "referrer" TEXT,
  "session_id" VARCHAR(255),
  "timestamp" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Webhooks
CREATE TABLE "webhooks" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID NOT NULL REFERENCES "organizations"("id"),
  "name" VARCHAR(255) NOT NULL,
  "url" TEXT NOT NULL,
  "events" JSONB NOT NULL,
  "secret" VARCHAR(255),
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "last_triggered_at" TIMESTAMP,
  "success_count" INTEGER NOT NULL DEFAULT 0,
  "failure_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id")
);

-- Webhook deliveries
CREATE TABLE "webhook_deliveries" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "webhook_id" UUID NOT NULL REFERENCES "webhooks"("id"),
  "event" VARCHAR(100) NOT NULL,
  "payload" JSONB NOT NULL,
  "status" VARCHAR(50) NOT NULL,
  "http_status" INTEGER,
  "response" TEXT,
  "error" TEXT,
  "attempt_count" INTEGER NOT NULL DEFAULT 1,
  "next_retry_at" TIMESTAMP,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "delivered_at" TIMESTAMP
);

-- API keys
CREATE TABLE "api_keys" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID NOT NULL REFERENCES "organizations"("id"),
  "name" VARCHAR(255) NOT NULL,
  "key_hash" VARCHAR(255) NOT NULL UNIQUE,
  "key_prefix" VARCHAR(20) NOT NULL,
  "scopes" JSONB NOT NULL,
  "rate_limit" INTEGER DEFAULT 1000,
  "usage_count" INTEGER NOT NULL DEFAULT 0,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "expires_at" TIMESTAMP,
  "last_used_at" TIMESTAMP,
  "last_used_ip" VARCHAR(45),
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "created_by" UUID NOT NULL REFERENCES "users"("id")
);

-- Moderation reports
CREATE TABLE "moderation_reports" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "type" VARCHAR(50) NOT NULL,
  "reason" VARCHAR(100) NOT NULL,
  "description" TEXT,
  "reported_id" UUID NOT NULL,
  "reported_type" VARCHAR(50) NOT NULL,
  "reported_user_id" UUID REFERENCES "users"("id"),
  "reporter_id" UUID NOT NULL REFERENCES "users"("id"),
  "status" VARCHAR(50) NOT NULL DEFAULT 'pending',
  "priority" VARCHAR(50) NOT NULL DEFAULT 'medium',
  "resolved_at" TIMESTAMP,
  "resolved_by" UUID REFERENCES "users"("id"),
  "resolution" TEXT,
  "action" VARCHAR(100),
  "metadata" JSONB DEFAULT '{}',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- AI insights
CREATE TABLE "ai_insights" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "user_id" UUID NOT NULL REFERENCES "users"("id"),
  "type" VARCHAR(100) NOT NULL,
  "insights" JSONB NOT NULL,
  "confidence" INTEGER NOT NULL,
  "context_type" VARCHAR(50),
  "context_id" UUID,
  "model" VARCHAR(100),
  "version" VARCHAR(50),
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "expires_at" TIMESTAMP
);

-- Referrals
CREATE TABLE "referrals" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "referrer_id" UUID NOT NULL REFERENCES "users"("id"),
  "referred_id" UUID REFERENCES "users"("id"),
  "referral_code" VARCHAR(50) NOT NULL UNIQUE,
  "status" VARCHAR(50) NOT NULL DEFAULT 'pending',
  "referrer_reward" INTEGER NOT NULL DEFAULT 500,
  "referred_reward" INTEGER NOT NULL DEFAULT 250,
  "completed_at" TIMESTAMP,
  "expires_at" TIMESTAMP,
  "metadata" JSONB DEFAULT '{}',
  "source" VARCHAR(100),
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- System settings
CREATE TABLE "system_settings" (
  "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  "organization_id" UUID REFERENCES "organizations"("id"),
  "key" VARCHAR(255) NOT NULL,
  "value" JSONB NOT NULL,
  "type" VARCHAR(50) NOT NULL DEFAULT 'json',
  "description" TEXT,
  "category" VARCHAR(100),
  "is_public" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updated_by" UUID REFERENCES "users"("id")
);

-- Create indexes for better performance
CREATE INDEX "organizations_slug_idx" ON "organizations"("slug");
CREATE INDEX "organizations_plan_idx" ON "organizations"("plan");

CREATE INDEX "users_email_idx" ON "users"("email");
CREATE INDEX "users_username_idx" ON "users"("username");
CREATE INDEX "users_role_idx" ON "users"("role");
CREATE INDEX "users_level_idx" ON "users"("level");
CREATE INDEX "users_organization_idx" ON "users"("organization_id");
CREATE INDEX "users_active_idx" ON "users"("is_active");

CREATE INDEX "categories_slug_idx" ON "curriculum_categories"("slug");
CREATE INDEX "categories_active_idx" ON "curriculum_categories"("is_active");
CREATE INDEX "categories_sort_idx" ON "curriculum_categories"("sort_order");

CREATE INDEX "modules_category_idx" ON "curriculum_modules"("category_id");
CREATE INDEX "modules_status_idx" ON "curriculum_modules"("status");
CREATE INDEX "modules_difficulty_idx" ON "curriculum_modules"("difficulty");
CREATE INDEX "modules_published_idx" ON "curriculum_modules"("published_at");
CREATE INDEX "modules_created_by_idx" ON "curriculum_modules"("created_by");
CREATE INDEX "modules_organization_idx" ON "curriculum_modules"("organization_id");
CREATE INDEX "modules_tags_idx" ON "curriculum_modules" USING GIN("tags");

CREATE INDEX "progress_user_idx" ON "user_progress"("user_id");
CREATE INDEX "progress_module_idx" ON "user_progress"("module_id");
CREATE INDEX "progress_completed_idx" ON "user_progress"("completed_at");
CREATE INDEX "progress_progress_idx" ON "user_progress"("progress");

CREATE INDEX "achievements_category_idx" ON "achievements"("category");
CREATE INDEX "achievements_rarity_idx" ON "achievements"("rarity");
CREATE INDEX "achievements_active_idx" ON "achievements"("is_active");
CREATE INDEX "achievements_organization_idx" ON "achievements"("organization_id");

CREATE INDEX "user_achievements_user_idx" ON "user_achievements"("user_id");
CREATE INDEX "user_achievements_unlocked_idx" ON "user_achievements"("unlocked_at");

CREATE INDEX "pods_invite_code_idx" ON "pods"("invite_code");
CREATE INDEX "pods_public_idx" ON "pods"("is_public");
CREATE INDEX "pods_active_idx" ON "pods"("is_active");
CREATE INDEX "pods_organization_idx" ON "pods"("organization_id");
CREATE INDEX "pods_activity_idx" ON "pods"("last_activity_at");

CREATE INDEX "pod_members_pod_idx" ON "pod_members"("pod_id");
CREATE INDEX "pod_members_user_idx" ON "pod_members"("user_id");
CREATE INDEX "pod_members_status_idx" ON "pod_members"("status");
CREATE INDEX "pod_members_role_idx" ON "pod_members"("role");

CREATE INDEX "missions_status_idx" ON "missions"("status");
CREATE INDEX "missions_start_date_idx" ON "missions"("start_date");
CREATE INDEX "missions_end_date_idx" ON "missions"("end_date");
CREATE INDEX "missions_difficulty_idx" ON "missions"("difficulty");
CREATE INDEX "missions_pod_idx" ON "missions"("pod_id");
CREATE INDEX "missions_organization_idx" ON "missions"("organization_id");
CREATE INDEX "missions_ai_generated_idx" ON "missions"("is_ai_generated");

CREATE INDEX "mission_participation_mission_idx" ON "mission_participation"("mission_id");
CREATE INDEX "mission_participation_user_idx" ON "mission_participation"("user_id");
CREATE INDEX "mission_participation_status_idx" ON "mission_participation"("status");
CREATE INDEX "mission_participation_completed_idx" ON "mission_participation"("completed_at");
CREATE INDEX "mission_participation_team_idx" ON "mission_participation"("team_id");

CREATE INDEX "chat_channels_pod_idx" ON "chat_channels"("pod_id");
CREATE INDEX "chat_channels_type_idx" ON "chat_channels"("type");
CREATE INDEX "chat_channels_last_message_idx" ON "chat_channels"("last_message_at");

CREATE INDEX "chat_messages_channel_idx" ON "chat_messages"("channel_id");
CREATE INDEX "chat_messages_user_idx" ON "chat_messages"("user_id");
CREATE INDEX "chat_messages_created_at_idx" ON "chat_messages"("created_at");
CREATE INDEX "chat_messages_parent_idx" ON "chat_messages"("parent_id");
CREATE INDEX "chat_messages_type_idx" ON "chat_messages"("message_type");

CREATE INDEX "notifications_user_idx" ON "notifications"("user_id");
CREATE INDEX "notifications_type_idx" ON "notifications"("type");
CREATE INDEX "notifications_read_idx" ON "notifications"("is_read");
CREATE INDEX "notifications_created_at_idx" ON "notifications"("created_at");
CREATE INDEX "notifications_scheduled_idx" ON "notifications"("scheduled_for");

CREATE INDEX "analytics_events_event_idx" ON "analytics_events"("event");
CREATE INDEX "analytics_events_user_idx" ON "analytics_events"("user_id");
CREATE INDEX "analytics_events_organization_idx" ON "analytics_events"("organization_id");
CREATE INDEX "analytics_events_timestamp_idx" ON "analytics_events"("timestamp");
CREATE INDEX "analytics_events_session_idx" ON "analytics_events"("session_id");

CREATE INDEX "webhooks_organization_idx" ON "webhooks"("organization_id");
CREATE INDEX "webhooks_active_idx" ON "webhooks"("is_active");
CREATE INDEX "webhooks_events_idx" ON "webhooks" USING GIN("events");

CREATE INDEX "webhook_deliveries_webhook_idx" ON "webhook_deliveries"("webhook_id");
CREATE INDEX "webhook_deliveries_status_idx" ON "webhook_deliveries"("status");
CREATE INDEX "webhook_deliveries_event_idx" ON "webhook_deliveries"("event");
CREATE INDEX "webhook_deliveries_created_at_idx" ON "webhook_deliveries"("created_at");
CREATE INDEX "webhook_deliveries_retry_idx" ON "webhook_deliveries"("next_retry_at");

CREATE INDEX "api_keys_key_hash_idx" ON "api_keys"("key_hash");
CREATE INDEX "api_keys_organization_idx" ON "api_keys"("organization_id");
CREATE INDEX "api_keys_active_idx" ON "api_keys"("is_active");
CREATE INDEX "api_keys_expires_idx" ON "api_keys"("expires_at");

CREATE INDEX "moderation_reports_type_idx" ON "moderation_reports"("type");
CREATE INDEX "moderation_reports_status_idx" ON "moderation_reports"("status");
CREATE INDEX "moderation_reports_priority_idx" ON "moderation_reports"("priority");
CREATE INDEX "moderation_reports_reported_idx" ON "moderation_reports"("reported_id", "reported_type");
CREATE INDEX "moderation_reports_reporter_idx" ON "moderation_reports"("reporter_id");
CREATE INDEX "moderation_reports_organization_idx" ON "moderation_reports"("organization_id");

CREATE INDEX "ai_insights_user_idx" ON "ai_insights"("user_id");
CREATE INDEX "ai_insights_type_idx" ON "ai_insights"("type");
CREATE INDEX "ai_insights_context_idx" ON "ai_insights"("context_type", "context_id");
CREATE INDEX "ai_insights_active_idx" ON "ai_insights"("is_active");
CREATE INDEX "ai_insights_expires_idx" ON "ai_insights"("expires_at");

CREATE INDEX "referrals_referrer_idx" ON "referrals"("referrer_id");
CREATE INDEX "referrals_referred_idx" ON "referrals"("referred_id");
CREATE INDEX "referrals_code_idx" ON "referrals"("referral_code");
CREATE INDEX "referrals_status_idx" ON "referrals"("status");
CREATE INDEX "referrals_organization_idx" ON "referrals"("organization_id");

CREATE INDEX "system_settings_category_idx" ON "system_settings"("category");
CREATE INDEX "system_settings_public_idx" ON "system_settings"("is_public");

-- Add unique constraints
ALTER TABLE "curriculum_categories" ADD CONSTRAINT "categories_org_slug_unique" UNIQUE ("organization_id", "slug");
ALTER TABLE "system_settings" ADD CONSTRAINT "system_settings_key_unique" UNIQUE ("organization_id", "key");

-- Create triggers for updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_organizations_updated_at BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_curriculum_categories_updated_at BEFORE UPDATE ON curriculum_categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_curriculum_modules_updated_at BEFORE UPDATE ON curriculum_modules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_progress_updated_at BEFORE UPDATE ON user_progress FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_achievements_updated_at BEFORE UPDATE ON achievements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pods_updated_at BEFORE UPDATE ON pods FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_missions_updated_at BEFORE UPDATE ON missions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_webhooks_updated_at BEFORE UPDATE ON webhooks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_moderation_reports_updated_at BEFORE UPDATE ON moderation_reports FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_system_settings_updated_at BEFORE UPDATE ON system_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert default organization
INSERT INTO organizations (name, slug, description, plan) VALUES 
('K-RESET Global', 'k-reset-global', 'Global K-RESET learning community', 'enterprise');
